# Blog info
blog_name: Attentiveness
slogan: Anyone Group
url: http://attentiveness.github.io

# Set avatar (Absolute url and relative url)
avatar: http://7xr0xq.com1.z0.glb.clouddn.com/anyone.jpeg

# Set favicon
favicon: http://7xr0xq.com1.z0.glb.clouddn.com/anyone.jpeg

# custom font-family 暂时只支持这3种英文字体
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

# Custom CSS style
personal_style: /css/forsigner.css

home:
  # background_image: /images/bg.jpg
  background_scheme: light # dark、light



# For seo
keywords: open source,react-native.android,ios


init_page_content: HOME_NAV  # HOME_NAV | POST

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/attentiveness
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
 # - name: 友链
 #   url: /link/
 #   target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
 # - name: 搜索
 #   url: /search/
 #   target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT


# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

about:
  - type: me
    icon: icon-user
    text_value:
    - "Attentiveness."
    - "Open Source Offering."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@attentiveness"
    text_value_url: https://github.com/attentiveness

# Stats
google_analytics:
#baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
# duoshuo_shortname: forsigner

project:
  - type: personal
    name: reading
    url: https://github.com/attentiveness/reading
    intro: Reading App Write In React-Native
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
